dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements.txt
script:
  - echo $(pwd)
  - cd AlgoTradingStuff
  - echo $(pwd)
  - gunicorn --bind 0.0.0.0:8000 Dashboard.wsgi